# Generated by Django 3.2.5 on 2021-12-04 11:59

from django.db import migrations, models
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ackley', '0003_auto_20211202_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Booking_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='Img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[294, 225], upload_to='static/images'),
        ),
    ]
