# Generated by Django 3.2.5 on 2021-11-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ackley', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Phone_number', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateField(verbose_name='Date booked')),
                ('Arrival', models.DateField()),
                ('No_of_guests', models.IntegerField(max_length=3)),
                ('No_of_days', models.IntegerField(max_length=3)),
            ],
        ),
    ]
